[project]
name = "open-science-workshop"
version = "0.1.0"
description = "Material for Open Science Workshop"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "rich>=14.2.0",
]

[project_urls]
Homepage = "https://github.com/matthiaskoenig/open-science-workshop"
Repository = "https://github.com/matthiaskoenig/open-science-workshop"
Documentation = "https://github.com/matthiaskoenig/open-science-workshop"
Issues = "https://github.com/matthiaskoenig/open-science-workshop/issues"

[project.scripts]
hello_world = "osw.hello_world:hello_world"

[tool.hatch.build.targets.wheel]
packages = ["src/osw"]

[tool.hatch.metadata]
allow-direct-references = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
